name: Integration Test

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 12 10 * *
  push:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - "*.md"
  pull_request:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - "*.md"

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: graycoreio/github-actions-magento2/supported-version@main
        id: supported-version
  integration-workflow:
    needs: compute_matrix
    uses: graycoreio/github-actions-magento2/.github/workflows/integration.yaml@main
    with:
      package_name: graycore/magento2-graphql-logger
      matrix: ${{ needs.compute_matrix.outputs.matrix }}
      test_command: ../../../vendor/bin/phpunit ../../../vendor/graycore/magento2-graphql-logger/Test/Integration
    secrets:
      composer_auth: ${{ secrets.COMPOSER_AUTH }}
